---
- name: Scenario 1 - Basic VM Provisioning
  hosts: localhost
  gather_facts: false
  vars:
    image_name: "ubuntu"
    flavor_name: "m1.small"
    network_name: "private"
    keypair_name: "demo-key"
    instance_name: "basic-vm"
    security_group_name: "basic-sg"
    volume_name: "basic-vm-volume"
    volume_size: 10
  
  tasks:
    - name: Ensure network exists
      openstack.cloud.network:
        name: "{{ network_name }}"
        state: present
      register: network_result
    
    - name: Ensure subnet exists for network
      openstack.cloud.subnet:
        name: "{{ network_name }}-subnet"
        network_name: "{{ network_name }}"
        cidr: "192.168.100.0/24"
        ip_version: 4
        dns_nameservers:
          - 8.8.8.8
          - 1.1.1.1
        enable_dhcp: true
        state: present
      when: network_result.changed
    
    - name: Create security group
      openstack.cloud.security_group:
        name: "{{ security_group_name }}"
        description: "Security group for basic VM"
        state: present
    
    - name: Add SSH rule to security group
      openstack.cloud.security_group_rule:
        security_group: "{{ security_group_name }}"
        protocol: tcp
        port_range_min: 22
        port_range_max: 22
        remote_ip_prefix: 0.0.0.0/0
        state: present
    
    - name: Add ICMP rule to security group
      openstack.cloud.security_group_rule:
        security_group: "{{ security_group_name }}"
        protocol: icmp
        remote_ip_prefix: 0.0.0.0/0
        state: present
    
    - name: Create SSH keypair if it doesn't exist
      openstack.cloud.keypair:
        name: "{{ keypair_name }}"
        public_key_file: "~/.ssh/id_rsa.pub"
        state: present
    
    - name: Create volume for VM
      openstack.cloud.volume:
        display_name: "{{ volume_name }}"
        size: "{{ volume_size }}"
        image: "{{ image_name }}"
        bootable: true
        state: present
      register: volume_result
    
    - name: Launch a basic VM with volume
      openstack.cloud.server:
        name: "{{ instance_name }}"
        flavor: "{{ flavor_name }}"
        network: "{{ network_name }}"
        key_name: "{{ keypair_name }}"
        security_groups:
          - "{{ security_group_name }}"
        boot_volume: "{{ volume_name }}"
        terminate_volume: false
        auto_ip: true
        wait: yes
        timeout: 300
      register: server_result
    
    - name: Display server information
      debug:
        msg: |
          Server created successfully:
          Name: {{ server_result.server.name }}
          ID: {{ server_result.server.id }}
          Status: {{ server_result.server.status }}
          Networks: {{ server_result.server.addresses }}
