---
- name: Scenario 16 - Full Production-Ready Stack
  hosts: localhost
  gather_facts: false
  vars:
    cloud_name: "mycloud"
    image_name: "ubuntu-24.04"
    flavor_name: "m1.small"
    network_name: "production-net"
    subnet_name: "production-subnet"
    router_name: "production-router"
    keypair_name: "demo-key"
    security_group_web: "prod-web-sg"
    security_group_db: "prod-db-sg"
    security_group_lb: "prod-lb-sg"
    lb_name: "prod-lb"
    web_prefix: "prod-web"
    web_count: 2
    db_name: "prod-db"
    volume_size_web: 15
    volume_size_db: 30
    volume_size_lb: 10

  tasks:
  # Network Infrastructure
  - name: Create production network
    openstack.cloud.network:
      cloud: "{{ cloud_name }}"
      name: "{{ network_name }}"
      state: present
    register: network_result

  - name: Create production subnet
    openstack.cloud.subnet:
      cloud: "{{ cloud_name }}"
      name: "{{ subnet_name }}"
      network_name: "{{ network_name }}"
      cidr: "192.168.200.0/24"
      gateway_ip: "192.168.200.1"
      ip_version: 4
      dns_nameservers:
      - 8.8.8.8
      - 1.1.1.1
      enable_dhcp: true
      state: present

  - name: Create production router
    openstack.cloud.router:
      cloud: "{{ cloud_name }}"
      name: "{{ router_name }}"
      network: "public"
      interfaces:
      - subnet: "{{ subnet_name }}"
      state: present
    register: router_result

  # Security Groups
  - name: Create load balancer security group
    openstack.cloud.security_group:
      cloud: "{{ cloud_name }}"
      name: "{{ security_group_lb }}"
      description: "Security group for load balancer"
      state: present

  - name: Add rules to LB security group
    openstack.cloud.security_group_rule:
      cloud: "{{ cloud_name }}"
      security_group: "{{ security_group_lb }}"
      protocol: "{{ item.protocol }}"
      port_range_min: "{{ item.port_min }}"
      port_range_max: "{{ item.port_max }}"
      remote_ip_prefix: "{{ item.cidr }}"
      state: present
    loop:
    - { protocol: tcp, port_min: 22, port_max: 22, cidr: "0.0.0.0/0" }
    - { protocol: tcp, port_min: 80, port_max: 80, cidr: "0.0.0.0/0" }
    - { protocol: tcp, port_min: 443, port_max: 443, cidr: "0.0.0.0/0" }
    - { protocol: icmp, port_min: -1, port_max: -1, cidr: "0.0.0.0/0" }
    ignore_errors: yes

  - name: Create web servers security group
    openstack.cloud.security_group:
      cloud: "{{ cloud_name }}"
      name: "{{ security_group_web }}"
      description: "Security group for web servers"
      state: present

  - name: Add rules to web security group
    openstack.cloud.security_group_rule:
      cloud: "{{ cloud_name }}"
      security_group: "{{ security_group_web }}"
      protocol: "{{ item.protocol }}"
      port_range_min: "{{ item.port_min }}"
      port_range_max: "{{ item.port_max }}"
      remote_ip_prefix: "{{ item.cidr }}"
      state: present
    loop:
    - { protocol: tcp, port_min: 22, port_max: 22, cidr: "0.0.0.0/0" }
    - { protocol: tcp, port_min: 80, port_max: 80, cidr: "192.168.200.0/24" }
    - { protocol: tcp, port_min: 443, port_max: 443, cidr: "192.168.200.0/24" }
    - { protocol: icmp, port_min: -1, port_max: -1, cidr: "0.0.0.0/0" }
    ignore_errors: yes

  - name: Create database security group
    openstack.cloud.security_group:
      cloud: "{{ cloud_name }}"
      name: "{{ security_group_db }}"
      description: "Security group for database server"
      state: present

  - name: Add rules to DB security group
    openstack.cloud.security_group_rule:
      cloud: "{{ cloud_name }}"
      security_group: "{{ security_group_db }}"
      protocol: "{{ item.protocol }}"
      port_range_min: "{{ item.port_min }}"
      port_range_max: "{{ item.port_max }}"
      remote_ip_prefix: "{{ item.cidr }}"
      state: present
    loop:
    - { protocol: tcp, port_min: 22, port_max: 22, cidr: "0.0.0.0/0" }
    - { protocol: tcp, port_min: 3306, port_max: 3306, cidr: "192.168.200.0/24" }
    - { protocol: icmp, port_min: -1, port_max: -1, cidr: "0.0.0.0/0" }
    ignore_errors: yes

  # SSH Keypair
  - name: Create SSH keypair
    openstack.cloud.keypair:
      cloud: "{{ cloud_name }}"
      name: "{{ keypair_name }}"
      public_key_file: "~/.ssh/id_rsa.pub"
      state: present

  # Volumes for all VMs
  - name: Provision volumes for web tier
    include_tasks: tasks/provision_web16_volume.yml
    loop: "{{ range(1, web_count + 1) | list }}"
    loop_control:
      loop_var: web_index

  - name: Provision database volume
    block:
    - name: Create volume for {{ db_name }}
      openstack.cloud.volume:
        cloud: "{{ cloud_name }}"
        name: "{{ db_name }}-volume"
        size: "{{ volume_size_db }}"
        image: "{{ image_name }}"
        bootable: true
        state: present
      register: db_volume_create

    - name: Record volume id for {{ db_name }}
      set_fact:
        db_volume_id: "{{ db_volume_create.volume.id | default(db_volume_create.id) }}"

    - name: Wait for {{ db_name }} volume readiness
      openstack.cloud.volume_info:
        cloud: "{{ cloud_name }}"
        filters:
          id: "{{ db_volume_id }}"
      register: db_volume_status
      until: >-
        (db_volume_status.volumes is defined) and (db_volume_status.volumes | length > 0) and ((db_volume_status.volumes[0].status | default('creating')) in ['available', 'in-use', 'error'])
      retries: 30
      delay: 5
      failed_when: >-
        db_volume_status.failed | default(false) or (
          (db_volume_status.volumes is defined)
          and (db_volume_status.volumes | length > 0)
          and ((db_volume_status.volumes[0].status | default('error')) == 'error')
        )

    - name: Keep {{ db_name }} volume bootable
      command: "openstack volume set --bootable {{ db_volume_id }}"
      environment:
        OS_CLOUD: "{{ cloud_name }}"
      ignore_errors: yes

    - name: Cache database volume details
      set_fact:
        db_volume_details: >-
          {{ db_volume_status.volumes[0]
             if (db_volume_status.volumes is defined and db_volume_status.volumes | length > 0)
             else (db_volume_create.volume if (db_volume_create.volume is defined) else db_volume_create) }}

  - name: Provision load balancer volume
    block:
    - name: Create volume for {{ lb_name }}
      openstack.cloud.volume:
        cloud: "{{ cloud_name }}"
        name: "{{ lb_name }}-volume"
        size: "{{ volume_size_lb }}"
        image: "{{ image_name }}"
        bootable: true
        state: present
      register: lb_volume_create

    - name: Record volume id for {{ lb_name }}
      set_fact:
        lb_volume_id: "{{ lb_volume_create.volume.id | default(lb_volume_create.id) }}"

    - name: Wait for {{ lb_name }} volume readiness
      openstack.cloud.volume_info:
        cloud: "{{ cloud_name }}"
        filters:
          id: "{{ lb_volume_id }}"
      register: lb_volume_status
      until: >-
        (lb_volume_status.volumes is defined) and (lb_volume_status.volumes | length > 0) and ((lb_volume_status.volumes[0].status | default('creating')) in ['available', 'in-use', 'error'])
      retries: 30
      delay: 5
      failed_when: >-
        lb_volume_status.failed | default(false) or (
          (lb_volume_status.volumes is defined)
          and (lb_volume_status.volumes | length > 0)
          and ((lb_volume_status.volumes[0].status | default('error')) == 'error')
        )

    - name: Keep {{ lb_name }} volume bootable
      command: "openstack volume set --bootable {{ lb_volume_id }}"
      environment:
        OS_CLOUD: "{{ cloud_name }}"
      ignore_errors: yes

    - name: Cache load balancer volume details
      set_fact:
        lb_volume_details: >-
          {{ lb_volume_status.volumes[0]
             if (lb_volume_status.volumes is defined and lb_volume_status.volumes | length > 0)
             else (lb_volume_create.volume if (lb_volume_create.volume is defined) else lb_volume_create) }}

  # Deploy VMs
  - name: Deploy database server
    openstack.cloud.server:
      cloud: "{{ cloud_name }}"
      name: "{{ db_name }}"
      flavor: "{{ flavor_name }}"
      network: "{{ network_name }}"
      key_name: "{{ keypair_name }}"
      security_groups:
      - "{{ security_group_db }}"
      boot_volume: "{{ db_volume_details.id }}"
      terminate_volume: false
      auto_ip: false
      wait: yes
      timeout: 600
      meta:
        role: "database"
        tier: "backend"
        environment: "production"
    register: db_server

  - name: Deploy web servers
    openstack.cloud.server:
      cloud: "{{ cloud_name }}"
      name: "{{ item.server_name }}"
      flavor: "{{ flavor_name }}"
      network: "{{ network_name }}"
      key_name: "{{ keypair_name }}"
      security_groups:
      - "{{ security_group_web }}"
      boot_volume: "{{ item.volume_id }}"
      terminate_volume: false
      auto_ip: false
      wait: yes
      timeout: 600
      meta:
        role: "webserver"
        tier: "application"
        environment: "production"
    loop: "{{ web_volume_records | default([]) }}"
    register: web_servers

  - name: Deploy load balancer
    openstack.cloud.server:
      cloud: "{{ cloud_name }}"
      name: "{{ lb_name }}"
      flavor: "{{ flavor_name }}"
      network: "{{ network_name }}"
      key_name: "{{ keypair_name }}"
      security_groups:
      - "{{ security_group_lb }}"
      boot_volume: "{{ lb_volume_details.id }}"
      terminate_volume: false
      auto_ip: true
      wait: yes
      timeout: 600
      meta:
        role: "loadbalancer"
        tier: "frontend"
        environment: "production"
    register: lb_server

  - name: Build web server summary list
    set_fact:
      web_server_summary_list: "{{ (web_server_summary_list | default([])) + [ web_summary_item ] }}"
    loop: "{{ web_servers.results | default([]) }}"
    when: web_servers is defined
    vars:
      web_summary_item:
        name: "{{ item.server.name }}"
        addresses: "{{ item.server.addresses }}"
        security_group: "{{ security_group_web }}"
        volume_id: "{{ (web_volume_records | selectattr('server_name', 'equalto', item.server.name) | map(attribute='volume_id') | list | first) }}"

  - name: Compose full stack deployment summary
    set_fact:
      fullstack_summary:
        network:
          name: "{{ network_name }}"
          subnet: "{{ subnet_name }}"
          router: "{{ router_name }}"
        load_balancer:
          name: "{{ lb_server.server.name }}"
          addresses: "{{ lb_server.server.addresses }}"
          security_group: "{{ security_group_lb }}"
          volume_id: "{{ lb_volume_details.id }}"
          volume_size_gb: "{{ lb_volume_details.size }}"
        web_servers: "{{ web_server_summary_list | default([]) }}"
        database:
          name: "{{ db_server.server.name }}"
          addresses: "{{ db_server.server.addresses }}"
          security_group: "{{ security_group_db }}"
          volume_id: "{{ db_volume_details.id }}"
          volume_size_gb: "{{ db_volume_details.size }}"
        security_groups:
        - name: "{{ security_group_lb }}"
          notes: "Public access on ports 80/443 and SSH"
        - name: "{{ security_group_web }}"
          notes: "Ingress from load balancer and SSH"
        - name: "{{ security_group_db }}"
          notes: "MySQL from web tier and SSH"
        volumes:
          load_balancer:
            id: "{{ lb_volume_details.id }}"
            size_gb: "{{ lb_volume_details.size }}"
          web: "{{ web_volume_records | default([]) }}"
          database:
            id: "{{ db_volume_details.id }}"
            size_gb: "{{ db_volume_details.size }}"
        next_steps:
        - "Access the load balancer and configure HAProxy"
        - "Deploy application code on web nodes"
        - "Configure MySQL backups on the database server"
        - "Test traffic via the load balancer public IP"

  - name: Display full stack deployment information
    debug:
      var: fullstack_summary
