---
- name: Scenario 7 - Multi-Network VMs
  hosts: localhost
  gather_facts: false
  vars:
    frontend_net: "frontend-net"
    backend_net: "backend-net"
    frontend_vm: "frontend"
    backend_vm: "backend"
    image_name: "ubuntu"
    flavor_name: "m1.small"
    keypair_name: "demo-key"
  tasks:
    - name: Create frontend and backend networks
      openstack.cloud.network:
        name: "{{ item }}"
        state: present
      loop:
        - "{{ frontend_net }}"
        - "{{ backend_net }}"

    - name: Create frontend and backend VMs
      openstack.cloud.server:
        name: "{{ item.name }}"
        image: "{{ image_name }}"
        flavor: "{{ flavor_name }}"
        networks:
          - name: "{{ item.net }}"
        key_name: "{{ keypair_name }}"
      loop:
        - { name: "{{ frontend_vm }}", net: "{{ frontend_net }}" }
        - { name: "{{ backend_vm }}", net: "{{ backend_net }}" }
