---
- name: Scenario 4 - Boot VM from Volume
  hosts: localhost
  gather_facts: false
  vars:
    cloud_name: "mycloud"
    image_name: "ubuntu-24.04"
    flavor_name: "m1.small"
    network_name: "private"
    keypair_name: "demo-key"
    volume_name: "boot-volume"
    instance_name: "vm-from-volume"
    volume_size: 10
    security_group_name: "boot-vm-sg"

  tasks:
  - name: Ensure network exists
    openstack.cloud.network:
      cloud: "{{ cloud_name }}"
      name: "{{ network_name }}"
      state: present
    register: network_result

  - name: Ensure subnet exists for network
    openstack.cloud.subnet:
      cloud: "{{ cloud_name }}"
      name: "{{ network_name }}-subnet"
      network_name: "{{ network_name }}"
      cidr: "192.168.100.0/24"
      ip_version: 4
      dns_nameservers:
      - 8.8.8.8
      - 1.1.1.1
      enable_dhcp: true
      state: present
    when: network_result.changed

  - name: Create security group
    openstack.cloud.security_group:
      cloud: "{{ cloud_name }}"
      name: "{{ security_group_name }}"
      description: "Security group for boot-from-volume VM"
      state: present

  - name: Add SSH rule to security group
    openstack.cloud.security_group_rule:
      cloud: "{{ cloud_name }}"
      security_group: "{{ security_group_name }}"
      protocol: tcp
      port_range_min: 22
      port_range_max: 22
      remote_ip_prefix: 0.0.0.0/0
      direction: ingress
      state: present
    ignore_errors: yes

  - name: Add ICMP rule to security group
    openstack.cloud.security_group_rule:
      cloud: "{{ cloud_name }}"
      security_group: "{{ security_group_name }}"
      protocol: icmp
      remote_ip_prefix: 0.0.0.0/0
      direction: ingress
      state: present
    ignore_errors: yes

  - name: Create SSH keypair if it doesn't exist
    openstack.cloud.keypair:
      cloud: "{{ cloud_name }}"
      name: "{{ keypair_name }}"
      public_key_file: "~/.ssh/id_rsa.pub"
      state: present

  - name: Create a bootable volume from image
    openstack.cloud.volume:
      cloud: "{{ cloud_name }}"
      display_name: "{{ volume_name }}"
      size: "{{ volume_size }}"
      image: "{{ image_name }}"
      bootable: true
      state: present
    register: volume_result

  - name: Wait for volume to be available
    openstack.cloud.volume_info:
      cloud: "{{ cloud_name }}"
      name: "{{ volume_name }}"
    register: volume_info
    until:
    - volume_info.volumes | length > 0
    - volume_info.volumes[0].status in ['available', 'in-use', 'error']
    retries: 30
    delay: 5
    failed_when: volume_info.volumes[0].status == 'error'

  - name: Ensure volume boot flag is set
    command: "openstack volume set --bootable {{ volume_name }}"
    environment:
      OS_CLOUD: "{{ cloud_name }}"
    ignore_errors: yes

  - name: Display volume details
    debug:
      msg: |
        Volume ready:
          Name: {{ volume_info.volumes[0].name }}
          ID: {{ volume_info.volumes[0].id }}
          Status: {{ volume_info.volumes[0].status }}
          Bootable: {{ volume_info.volumes[0].is_bootable }}

  - name: Launch VM from volume
    openstack.cloud.server:
      cloud: "{{ cloud_name }}"
      name: "{{ instance_name }}"
      flavor: "{{ flavor_name }}"
      network: "{{ network_name }}"
      key_name: "{{ keypair_name }}"
      security_groups:
      - "{{ security_group_name }}"
      boot_volume: "{{ volume_name }}"
      terminate_volume: false
      auto_ip: true
      wait: yes
      timeout: 600
    register: server_result

  - name: Display VM information
    debug:
      msg: |
        VM created successfully from volume:
        Name: {{ server_result.server.name }}
        ID: {{ server_result.server.id }}
        Status: {{ server_result.server.status }}
        Boot Volume: {{ volume_name }} ({{ volume_size }}GB)
        Networks: {{ server_result.server.addresses }}
