---
- name: Scenario 2 - Create Network and Subnet
  hosts: localhost
  gather_facts: false
  vars:
    network_name: "training-net"
    subnet_name: "training-subnet"
    cidr: "192.168.50.0/24"
    dns_nameservers:
      - 8.8.8.8
      - 1.1.1.1
  tasks:
    - name: Create internal network
      openstack.cloud.network:
        name: "{{ network_name }}"
        state: present

    - name: Create subnet
      openstack.cloud.subnet:
        name: "{{ subnet_name }}"
        network_name: "{{ network_name }}"
        cidr: "{{ cidr }}"
        ip_version: 4
        dns_nameservers: "{{ dns_nameservers }}"
        enable_dhcp: true
