---
- name: Scenario 13 - Using Vaulted Variables
  hosts: localhost
  gather_facts: false
  vars_files:
    - secrets/vault.yml
  tasks:
    - name: Show decrypted secret
      debug:
        msg: "Vault password is {{ vault_password }}"
