---
- name: Scenario 14 - HAProxy Load Balancer with Backend VMs
  hosts: localhost
  gather_facts: false
  vars:
    cloud_name: "mycloud"
    image_name: "ubuntu-22.04"
    flavor_name: "m1.small"
    frontend_name: "haproxy"
    backend_prefix: "web"
    backend_count: 2
    network_name: "private"
    keypair_name: "demo-key"
    security_group_name: "haproxy-sg"
    haproxy_volume: "haproxy-volume"
    volume_size: 10

  tasks:
  - name: Ensure network exists
    openstack.cloud.network:
      cloud: "{{ cloud_name }}"
      name: "{{ network_name }}"
      state: present
    register: network_result

  - name: Ensure subnet exists for network
    openstack.cloud.subnet:
      cloud: "{{ cloud_name }}"
      name: "{{ network_name }}-subnet"
      network_name: "{{ network_name }}"
      cidr: "192.168.100.0/24"
      ip_version: 4
      dns_nameservers:
      - 8.8.8.8
      - 1.1.1.1
      enable_dhcp: true
      state: present
    when: network_result.changed

  - name: Create security group
    openstack.cloud.security_group:
      cloud: "{{ cloud_name }}"
      name: "{{ security_group_name }}"
      description: "Security group for HAProxy and backends"
      state: present

  - name: Add SSH rule to security group
    openstack.cloud.security_group_rule:
      cloud: "{{ cloud_name }}"
      security_group: "{{ security_group_name }}"
      protocol: tcp
      port_range_min: 22
      port_range_max: 22
      remote_ip_prefix: 0.0.0.0/0
      state: present
    ignore_errors: yes

  - name: Add HTTP rule to security group
    openstack.cloud.security_group_rule:
      cloud: "{{ cloud_name }}"
      security_group: "{{ security_group_name }}"
      protocol: tcp
      port_range_min: 80
      port_range_max: 80
      remote_ip_prefix: 0.0.0.0/0
      state: present
    ignore_errors: yes

  - name: Add HTTPS rule to security group
    openstack.cloud.security_group_rule:
      cloud: "{{ cloud_name }}"
      security_group: "{{ security_group_name }}"
      protocol: tcp
      port_range_min: 443
      port_range_max: 443
      remote_ip_prefix: 0.0.0.0/0
      state: present
    ignore_errors: yes

  - name: Add ICMP rule to security group
    openstack.cloud.security_group_rule:
      cloud: "{{ cloud_name }}"
      security_group: "{{ security_group_name }}"
      protocol: icmp
      remote_ip_prefix: 0.0.0.0/0
      state: present
    ignore_errors: yes

  - name: Create SSH keypair if it doesn't exist
    openstack.cloud.keypair:
      cloud: "{{ cloud_name }}"
      name: "{{ keypair_name }}"
      public_key_file: "~/.ssh/id_rsa.pub"
      state: present

  - name: Create volumes for backend VMs
    openstack.cloud.volume:
      cloud: "{{ cloud_name }}"
      display_name: "{{ backend_prefix }}{{ item }}-volume"
      size: "{{ volume_size }}"
      image: "{{ image_name }}"
      bootable: true
      state: present
    loop: "{{ range(1, backend_count + 1) | list }}"

  - name: Deploy backend VMs
    openstack.cloud.server:
      cloud: "{{ cloud_name }}"
      name: "{{ backend_prefix }}{{ item }}"
      flavor: "{{ flavor_name }}"
      network: "{{ network_name }}"
      key_name: "{{ keypair_name }}"
      security_groups:
      - "{{ security_group_name }}"
      boot_volume: "{{ backend_prefix }}{{ item }}-volume"
      terminate_volume: false
      auto_ip: true
      wait: yes
      timeout: 600
      meta:
        role: "backend"
        group: "webservers"
    loop: "{{ range(1, backend_count + 1) | list }}"
    register: backend_servers

  - name: Create volume for HAProxy VM
    openstack.cloud.volume:
      cloud: "{{ cloud_name }}"
      display_name: "{{ haproxy_volume }}"
      size: "{{ volume_size }}"
      image: "{{ image_name }}"
      bootable: true
      state: present
    register: haproxy_volume_result

  - name: Deploy HAProxy VM
    openstack.cloud.server:
      cloud: "{{ cloud_name }}"
      name: "{{ frontend_name }}"
      flavor: "{{ flavor_name }}"
      network: "{{ network_name }}"
      key_name: "{{ keypair_name }}"
      security_groups:
      - "{{ security_group_name }}"
      boot_volume: "{{ haproxy_volume }}"
      terminate_volume: false
      auto_ip: true
      wait: yes
      timeout: 600
      meta:
        role: "loadbalancer"
        backends: "{{ backend_count }}"
    register: haproxy_server

  - name: Display HAProxy deployment information
    debug:
      msg: |
        HAProxy Load Balancer deployed successfully:

        HAProxy (Frontend):
          Name: {{ haproxy_server.server.name }}
          IP: {{ haproxy_server.server.addresses }}

        Backend Servers ({{ backend_count }}):
        {% for server in backend_servers.results %}
          - {{ server.server.name }}: {{ server.server.addresses }}
        {% endfor %}

        Next steps:
        1. SSH to HAProxy: ssh -i ~/.ssh/id_rsa ubuntu@<haproxy-ip>
        2. Configure HAProxy to balance traffic to backend servers
        3. Install and configure web servers on backend VMs
