---
- name: Teardown Scenario 12 - LAMP Stack
  hosts: localhost
  gather_facts: false
  vars:
    network_name: "lamp-network"
    subnet_name: "lamp-subnet"
    security_group_name: "lamp-sg"
    web_volume: "lamp-web-volume"
    db_volume: "lamp-db-volume"
  
  tasks:
    - name: Delete LAMP VMs
      openstack.cloud.server:
        name: "{{ item }}"
        state: absent
        wait: yes
        timeout: 180
      loop:
        - lamp-web
        - lamp-db
    
    - name: Wait for VMs to be fully deleted
      pause:
        seconds: 10
    
    - name: Delete volumes
      openstack.cloud.volume:
        display_name: "{{ item }}"
        state: absent
      loop:
        - "{{ web_volume }}"
        - "{{ db_volume }}"
    
    - name: Delete subnet
      openstack.cloud.subnet:
        name: "{{ subnet_name }}"
        state: absent
    
    - name: Delete network
      openstack.cloud.network:
        name: "{{ network_name }}"
        state: absent
    
    - name: Delete security group
      openstack.cloud.security_group:
        name: "{{ security_group_name }}"
        state: absent
    
    - name: Display teardown completion
      debug:
        msg: "LAMP stack resources have been cleaned up successfully"
