---
- name: Teardown Scenario 3 - Router
  hosts: localhost
  vars:
    cloud_name: "mycloud"
  tasks:
    - name: Detach subnet from router
      command: "openstack router remove subnet training-router training-subnet"
      environment:
        OS_CLOUD: "{{ cloud_name }}"
      changed_when: true
      ignore_errors: true

    - name: Delete router
      openstack.cloud.router:
        name: "training-router"
        state: absent
