---
- name: Teardown Scenario 9 - Role-based Multi-VM
  hosts: localhost
  tasks:
    - name: Delete all VMs from the role deployment
      openstack.cloud.server:
        name: "{{ item }}"
        state: absent
      loop:
        - vm1
        - vm2
      ignore_errors: true
