---
- name: OpenStack Fullstack Infrastructure Deployment
  hosts: localhost
  gather_facts: false
  vars:
    cloud_name: "mycloud"
    image_name: "ubuntu-24.04"
    flavor_name: "m1.small"

    network_name: "fullstack-net"
    subnet_name: "fullstack-subnet"
    subnet_cidr: "192.168.210.0/24"
    router_name: "fullstack-router"
    external_network: "public"

    keypair_name: "fullstack-key"
    keypair_public_key: "~/.ssh/id_rsa.pub"

    security_group_lb: "fullstack-lb-sg"
    security_group_web: "fullstack-web-sg"
    security_group_db: "fullstack-db-sg"

    lb_name: "fullstack-lb"
    lb_volume_size: 10

    web_prefix: "fullstack-web"
    web_count: 2
    web_volume_size: 15

    db_name: "fullstack-db"
    db_volume_size: 30

  tasks:
  - name: Ensure application network exists
    openstack.cloud.network:
      cloud: "{{ cloud_name }}"
      name: "{{ network_name }}"
      state: present
    register: network_result

  - name: Ensure application subnet exists
    openstack.cloud.subnet:
      cloud: "{{ cloud_name }}"
      name: "{{ subnet_name }}"
      network_name: "{{ network_name }}"
      cidr: "{{ subnet_cidr }}"
      ip_version: 4
      enable_dhcp: true
      dns_nameservers:
      - 8.8.8.8
      - 1.1.1.1
      state: present

  - name: Ensure router exists
    openstack.cloud.router:
      cloud: "{{ cloud_name }}"
      name: "{{ router_name }}"
      network: "{{ external_network }}"
      interfaces:
      - subnet: "{{ subnet_name }}"
      state: present
    register: router_result

  - name: Ensure security groups exist
    openstack.cloud.security_group:
      cloud: "{{ cloud_name }}"
      name: "{{ item.name }}"
      description: "{{ item.description }}"
      state: present
    loop:
    - { name: "{{ security_group_lb }}", description: "Load balancer security group" }
    - { name: "{{ security_group_web }}", description: "Web tier security group" }
    - { name: "{{ security_group_db }}", description: "Database security group" }

  - name: Configure security group rules
    openstack.cloud.security_group_rule:
      cloud: "{{ cloud_name }}"
      security_group: "{{ item.security_group }}"
      protocol: "{{ item.protocol }}"
      port_range_min: "{{ item.port_min }}"
      port_range_max: "{{ item.port_max }}"
      remote_ip_prefix: "{{ item.cidr }}"
      direction: ingress
      state: present
    loop:
    - { security_group: "{{ security_group_lb }}", protocol: tcp, port_min: 22, port_max: 22, cidr: "0.0.0.0/0" }
    - { security_group: "{{ security_group_lb }}", protocol: tcp, port_min: 80, port_max: 80, cidr: "0.0.0.0/0" }
    - { security_group: "{{ security_group_lb }}", protocol: tcp, port_min: 443, port_max: 443, cidr: "0.0.0.0/0" }
    - { security_group: "{{ security_group_lb }}", protocol: icmp, port_min: -1, port_max: -1, cidr: "0.0.0.0/0" }
    - { security_group: "{{ security_group_web }}", protocol: tcp, port_min: 22, port_max: 22, cidr: "0.0.0.0/0" }
    - { security_group: "{{ security_group_web }}", protocol: tcp, port_min: 80, port_max: 80, cidr: "0.0.0.0/0" }
    - { security_group: "{{ security_group_web }}", protocol: tcp, port_min: 443, port_max: 443, cidr: "0.0.0.0/0" }
    - { security_group: "{{ security_group_web }}", protocol: icmp, port_min: -1, port_max: -1, cidr: "0.0.0.0/0" }
    - { security_group: "{{ security_group_db }}", protocol: tcp, port_min: 22, port_max: 22, cidr: "0.0.0.0/0" }
    - { security_group: "{{ security_group_db }}", protocol: tcp, port_min: 3306, port_max: 3306, cidr: "{{ subnet_cidr }}" }
    - { security_group: "{{ security_group_db }}", protocol: icmp, port_min: -1, port_max: -1, cidr: "0.0.0.0/0" }
    ignore_errors: yes

  - name: Ensure SSH key pair exists
    openstack.cloud.keypair:
      cloud: "{{ cloud_name }}"
      name: "{{ keypair_name }}"
      public_key_file: "{{ keypair_public_key }}"
      state: present

  - name: Provision web tier volumes
    vars:
      current_web_name: "{{ web_prefix }}{{ web_index }}"
      current_web_volume: "{{ web_prefix }}{{ web_index }}-volume"
    block:
    - name: Create volume for {{ current_web_name }}
      openstack.cloud.volume:
        cloud: "{{ cloud_name }}"
        name: "{{ current_web_volume }}"
        size: "{{ web_volume_size }}"
        image: "{{ image_name }}"
        bootable: true
        state: present
      register: web_volume_create

    - name: Record volume id for {{ current_web_volume }}
      set_fact:
        current_web_volume_id: "{{ web_volume_create.volume.id | default(web_volume_create.id) }}"

    - name: Wait for {{ current_web_volume }} to become ready
      openstack.cloud.volume_info:
        cloud: "{{ cloud_name }}"
        filters:
          id: "{{ current_web_volume_id }}"
      register: web_volume_status
      until: >-
        (web_volume_status.volumes is defined) and (web_volume_status.volumes | length > 0) and ((web_volume_status.volumes[0].status | default('creating')) in ['available', 'in-use', 'error'])
      retries: 30
      delay: 5
      failed_when: >-
        web_volume_status.failed | default(false) or (
          (web_volume_status.volumes is defined)
          and (web_volume_status.volumes | length > 0)
          and ((web_volume_status.volumes[0].status | default('error')) == 'error')
        )

    - name: Ensure {{ current_web_volume }} is bootable
      command: "openstack volume set --bootable {{ current_web_volume_id }}"
      environment:
        OS_CLOUD: "{{ cloud_name }}"
      ignore_errors: yes

    - name: Cache {{ current_web_volume }} details
      set_fact:
        current_web_volume_details: >-
          {{ web_volume_status.volumes[0]
             if (web_volume_status.volumes is defined and web_volume_status.volumes | length > 0)
             else (web_volume_create.volume if (web_volume_create.volume is defined) else web_volume_create) }}

    - name: Compose {{ current_web_volume }} metadata
      set_fact:
        current_web_volume_record:
          server_name: "{{ current_web_name }}"
          volume_name: "{{ current_web_volume }}"
          volume_id: "{{ current_web_volume_details.id }}"
          status: "{{ current_web_volume_details.status }}"
          bootable: "{{ current_web_volume_details.is_bootable }}"

    - name: Append {{ current_web_volume }} metadata
      set_fact:
        web_volume_records: "{{ (web_volume_records | default([])) + [ current_web_volume_record ] }}"
    loop: "{{ range(1, web_count + 1) | list }}"
    loop_control:
      loop_var: web_index

  - name: Provision database volume
    block:
    - name: Create volume for {{ db_name }}
      openstack.cloud.volume:
        cloud: "{{ cloud_name }}"
        name: "{{ db_name }}-volume"
        size: "{{ db_volume_size }}"
        image: "{{ image_name }}"
        bootable: true
        state: present
      register: db_volume_create

    - name: Record volume id for {{ db_name }}
      set_fact:
        db_volume_id: "{{ db_volume_create.volume.id | default(db_volume_create.id) }}"

    - name: Wait for {{ db_name }} volume to become ready
      openstack.cloud.volume_info:
        cloud: "{{ cloud_name }}"
        filters:
          id: "{{ db_volume_id }}"
      register: db_volume_status
      until: >-
        (db_volume_status.volumes is defined) and (db_volume_status.volumes | length > 0) and ((db_volume_status.volumes[0].status | default('creating')) in ['available', 'in-use', 'error'])
      retries: 30
      delay: 5
      failed_when: >-
        db_volume_status.failed | default(false) or (
          (db_volume_status.volumes is defined)
          and (db_volume_status.volumes | length > 0)
          and ((db_volume_status.volumes[0].status | default('error')) == 'error')
        )

    - name: Ensure {{ db_name }} volume is bootable
      command: "openstack volume set --bootable {{ db_volume_id }}"
      environment:
        OS_CLOUD: "{{ cloud_name }}"
      ignore_errors: yes

    - name: Cache database volume details
      set_fact:
        db_volume_details: >-
          {{ db_volume_status.volumes[0]
             if (db_volume_status.volumes is defined and db_volume_status.volumes | length > 0)
             else (db_volume_create.volume if (db_volume_create.volume is defined) else db_volume_create) }}

  - name: Provision load balancer volume
    block:
    - name: Create volume for {{ lb_name }}
      openstack.cloud.volume:
        cloud: "{{ cloud_name }}"
        name: "{{ lb_name }}-volume"
        size: "{{ lb_volume_size }}"
        image: "{{ image_name }}"
        bootable: true
        state: present
      register: lb_volume_create

    - name: Record volume id for {{ lb_name }}
      set_fact:
        lb_volume_id: "{{ lb_volume_create.volume.id | default(lb_volume_create.id) }}"

    - name: Wait for {{ lb_name }} volume to become ready
      openstack.cloud.volume_info:
        cloud: "{{ cloud_name }}"
        filters:
          id: "{{ lb_volume_id }}"
      register: lb_volume_status
      until: >-
        (lb_volume_status.volumes is defined) and (lb_volume_status.volumes | length > 0) and ((lb_volume_status.volumes[0].status | default('creating')) in ['available', 'in-use', 'error'])
      retries: 30
      delay: 5
      failed_when: >-
        lb_volume_status.failed | default(false) or (
          (lb_volume_status.volumes is defined)
          and (lb_volume_status.volumes | length > 0)
          and ((lb_volume_status.volumes[0].status | default('error')) == 'error')
        )

    - name: Ensure {{ lb_name }} volume is bootable
      command: "openstack volume set --bootable {{ lb_volume_id }}"
      environment:
        OS_CLOUD: "{{ cloud_name }}"
      ignore_errors: yes

    - name: Cache load balancer volume details
      set_fact:
        lb_volume_details: >-
          {{ lb_volume_status.volumes[0]
             if (lb_volume_status.volumes is defined and lb_volume_status.volumes | length > 0)
             else (lb_volume_create.volume if (lb_volume_create.volume is defined) else lb_volume_create) }}

  - name: Launch web application servers
    openstack.cloud.server:
      cloud: "{{ cloud_name }}"
      name: "{{ item.server_name }}"
      flavor: "{{ flavor_name }}"
      network: "{{ network_name }}"
      key_name: "{{ keypair_name }}"
      security_groups:
      - "{{ security_group_web }}"
      boot_volume: "{{ item.volume_id }}"
      terminate_volume: false
      auto_ip: false
      wait: yes
      timeout: 600
      meta:
        role: "web"
        tier: "application"
    loop: "{{ web_volume_records | default([]) }}"
    register: web_servers

  - name: Launch database server
    openstack.cloud.server:
      cloud: "{{ cloud_name }}"
      name: "{{ db_name }}"
      flavor: "{{ flavor_name }}"
      network: "{{ network_name }}"
      key_name: "{{ keypair_name }}"
      security_groups:
      - "{{ security_group_db }}"
      boot_volume: "{{ db_volume_details.id }}"
      terminate_volume: false
      auto_ip: false
      wait: yes
      timeout: 600
      meta:
        role: "database"
        tier: "backend"
    register: db_server

  - name: Launch load balancer server
    openstack.cloud.server:
      cloud: "{{ cloud_name }}"
      name: "{{ lb_name }}"
      flavor: "{{ flavor_name }}"
      network: "{{ network_name }}"
      key_name: "{{ keypair_name }}"
      security_groups:
      - "{{ security_group_lb }}"
      boot_volume: "{{ lb_volume_details.id }}"
      terminate_volume: false
      auto_ip: true
      wait: yes
      timeout: 600
      meta:
        role: "loadbalancer"
        tier: "frontend"
    register: lb_server

  - name: Display deployment summary
    debug:
      msg: |
        ╔═══════════════════════════════════════════════════════════════╗
        ║                 OpenStack Fullstack Deployment                ║
        ╚═══════════════════════════════════════════════════════════════╝

        Networking:
          - Network: {{ network_name }}
          - Subnet: {{ subnet_name }} ({{ subnet_cidr }})
          - Router: {{ router_name }} (uplink: {{ external_network }})

        Load Balancer:
          - Name: {{ lb_server.server.name }}
          - IPs: {{ lb_server.server.addresses }}
          - Volume: {{ lb_volume_details.id }} ({{ lb_volume_details.size }} GB)

        Web Tier ({{ web_volume_records | length }} servers):
        {% for web in (web_servers.results | default([])) %}
          {% set vol_id = (web_volume_records | default([]) | selectattr('server_name', 'equalto', web.server.name) | map(attribute='volume_id') | list | first) %}
          - {{ web.server.name }} :: {{ web.server.addresses }} :: Volume {{ vol_id | default('n/a') }}
        {% endfor %}

        Database:
          - Name: {{ db_server.server.name }}
          - IPs: {{ db_server.server.addresses }}
          - Volume: {{ db_volume_details.id }} ({{ db_volume_details.size }} GB)

        Security Groups:
          - {{ security_group_lb }} (22, 80, 443, ICMP from 0.0.0.0/0)
          - {{ security_group_web }} (22, 80, 443, ICMP from 0.0.0.0/0)
          - {{ security_group_db }} (22 from 0.0.0.0/0, 3306 from {{ subnet_cidr }})

        Next steps:
          1. SSH to {{ lb_server.server.name }} using key {{ keypair_name }} and configure reverse proxy.
          2. Deploy application code on web tier nodes.
          3. Configure database replication/backups as required.
          4. Update DNS records to point to the load balancer public IP.
