---
- name: Create SSH keypair
  openstack.cloud.keypair:
    name: "{{ keypair_name }}"
    public_key_file: "~/.ssh/id_rsa.pub"

- name: Launch VM
  openstack.cloud.server:
    name: "{{ instance_name }}"
    image: "{{ image_name }}"
    flavor: "{{ flavor_name }}"
    network: "{{ network_name }}"
    key_name: "{{ keypair_name }}"
    auto_ip: true
