---
- name: Create volume from image
  openstack.cloud.volume:
    display_name: "{{ volume_name }}"
    size: "{{ volume_size }}"
    image: "{{ image_name }}"
    bootable: true
    state: present

- name: Launch VM from volume
  openstack.cloud.server:
    name: "{{ instance_name }}"
    flavor: "{{ flavor_name }}"
    network: "{{ network_name }}"
    key_name: "{{ keypair_name }}"
    boot_volume: "{{ volume_name }}"
    auto_ip: true
