---
cloud_name: "mycloud"
image_name: "ubuntu-24.04"
flavor_name: "m1.small"
network_name: "private"
keypair_name: "demo-key"
vm_definitions:
  - name: "vm1"
    auto_ip: true
  - name: "vm2"
    auto_ip: true
